### ISSUE TITLE
Disable certificate verification

### ISSUE THREAD

**Issue by mpeaybiz** [Botmock/botmock-lex-export#15]
**Issue Overview**
When running this code within enterprise network, i get the following error:
failed, reason: self signed certificate in certificate chain

**Steps To Reproduce**
Attempt export of Botmock project within corporate network.

**Expected Behavior**
Expect to export project per instructions.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Win 10
 - NPM Version: 10.15.3

**Additional Context**
We are able to run again the API using Postman, which allows SSL certificate verification to be turned off, so assuming this is the issue.

**Comment by nonnontrivial** [comment]
Thank you for opening this @mpeaybiz . It sounds like it could be related to the HTTP client we are using, `node-fetch`.

**Comment by obaid** [comment]
Thanks for reporting the issue @mpeaybiz 

Our team is investigating the cause for this. However, there is a method that you can use to unblock yourself. We don't recommend running in production with this work around.

You can disable certificate verification by:

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` 

We will update this ticket with more details as soon as possible.

**Comment by mpeaybiz** [comment]
We are seeing this error now: 
> [2020-03-09T19:27:06.100Z] FetchError: request to https://app.botmock.com/api/teams/@xxx-removed-xxx/projects/@xxx-removed-xxx/boards/@xxx-removed-xxx failed, reason: read ECONNRESET    at ClientRequest.<anonymous> (C:\Users\xxx\Documents\GitHub\botmock-lex-export\node_modules\node-fetch\lib\index.js:1455:11)

**Comment by obaid** [comment]
Hi @mpeaybiz, Can you please try the changes in the PR https://github.com/Botmock/botmock-lex-export/pull/16?

Thanks

**Comment by mpeaybiz** [comment]
Hi Obaid, we will be looking at it this afternoon.

Thanks for your follow-up!

**Comment by mpeaybiz** [comment]
Hi Obaid,

We have tried re-running with the latest code from http-agent end of day yesterday with the same results below (ids redacted).

We learned yesterday that another team will be looking into an automated export solution, so we need to pause this work. I would assume the other team will pick it up where we left off, or look to develop a customer solution based on business requirements.

Appreciate all your help and will stay alert for any changes to the project.

Regards,
Matt

----------------------------------------------------------------------------------------------------------------------------------
C:\Users\xxxxx\Documents\GitHub\botmock-lex-export-http-agent> npm start

> botmock-lex-export@2.0.0<mailto:botmock-lex-export@2.0.0> start C:\Users\mpeay\Documents\GitHub\botmock-lex-export-http-agent
> ts-node index.ts

> [2020-03-19T13:55:04.962Z] creating output directories
> [2020-03-19T13:55:04.973Z] fetching project data
> [2020-03-19T13:55:05.267Z] FetchError: request to https://app.botmock.com/api/teams/@12345/projects/@qwertyuiop/intents failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\xxxxx\Documents\GitHub\botmock-lex-export-http-agent\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)




Public Information
From: Pearce, Matthew
Sent: Thursday, March 19, 2020 9:01 AM
To: Botmock/botmock-lex-export <reply@reply.github.com>; Botmock/botmock-lex-export <botmock-lex-export@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [External] Re: [Botmock/botmock-lex-export] Disable certificate verification (#15)

Hi Obaid, we will be looking at it this afternoon.

Thanks for your follow-up!

**Comment by prajakta8** [comment]
Hi,

I could resolve the issue. Following are my inputs.

Disabled certificate verification by adding below code in index.ts,

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
`

Tried adding https-proxy-agent directly in the \@botmock\client\lib\fetch\index.js and modified the agent in fetch call which resolved the ECONNRESET error,

```
const HttpsProxyAgent = require('https-proxy-agent');
const proxy = 'http:[proxyurl]:[port]'
```

On line 62: `agent: new HttpsProxyAgent(proxy),`

This worked and I got the output json.
